version: "3"
services:

  web:
    image: url:urlshortner
    working_dir: /app
    container_name: urlcontainer
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - .:/app
    command:
      - tail
      - -f
      - /dev/null
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - urlnetwork

  db:
    image: postgres:latest
    container_name: postgrescontainer
    environment:
      POSTGRES_DB: uriocean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - urlnetwork

networks:
  urlnetwork:
