# Generated by Django 3.2 on 2023-09-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originaluri', models.TextField(blank=True, null=True)),
                ('shorturi', models.UUIDField(unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('expiryAt', models.DateTimeField()),
            ],
        ),
    ]
