# Generated by Django 3.2 on 2023-09-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstore',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlstore',
            name='expiryAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='urlstore',
            name='shorturi',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='urlstore',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
