# Generated by Django 3.2 on 2023-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_auto_20230921_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstore',
            name='expiryAt',
            field=models.DateField(null=True),
        ),
    ]
