# Generated by Django 3.2 on 2023-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_alter_urlstore_expiryat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstore',
            name='shorturi',
            field=models.URLField(null=True, unique=True),
        ),
    ]
