# Generated by Django 4.2.6 on 2023-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0004_alter_urlstore_shorturi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstore',
            name='shorturi',
            field=models.CharField(null=True, unique=True),
        ),
    ]
